theme: jekyll-theme-slate
description: Sitio personal de Luis Alberto Cantos. Gestor de Proyectos Web experto en herramientas de Google y con conocimientos de SEO.
image: http://d1qmdf3vop2l07.cloudfront.net/cantaloupe-spoonbill.cloudvent.net/compressed/fbc3aba26b926442ca8e61f79b65a384.svg
